Roll Call
tonybaloney/vscode-pets pull request #175
Opened 2022-10-03 18:11 UTC by Harry-Hopkinson

Fixes #172

2022-10-03 18:12 UTC, Harry-Hopkinson commented
@tonybaloney What format would you like to be printed out? Currently I have `Type ${ pet.type }, Name ${pet.pet.name()}, Color ${ pet.color } Assigned for Duty!`.

2022-10-03 18:15 UTC, Harry-Hopkinson commented
I have updated the main-bundle by running npm run compile. It is just code from other people that has not been built.

2022-10-04 03:47 UTC, tonybaloney requested changes

2022-10-04 03:47 UTC, tonybaloney commented on package.json
> +                "title": "Rollcall",
Hyphenate to "Roll-call"

2022-10-04 03:47 UTC, tonybaloney commented on package.json
> +                "command": "vscode-pets.rollcall",
Change the command to `roll-call` as well so it's consistent with the backend

2022-10-04 03:47 UTC, tonybaloney commented on media/main-bundle.js
> +                        text: `Type ${pet.type}, Name ${pet.pet.name()}, Color ${pet.color} Assigned for Duty!`,
`${pet.pet.emoji()} ${pet.pet.name()} (${pet.color}: ${pet.pet.hello()}`

Add a `.hello()` method to the pet interface so each pet can have a custom hello message.

2022-10-04 03:47 UTC, tonybaloney commented on src/extension/extension.ts
> +        vscode.commands.registerCommand('vscode-pets.rollcall', async () => {
Update to `roll-call`

2022-10-04 03:47 UTC, tonybaloney commented on src/panel/main.ts
> +                pets.forEach((pet) => {
As above (see custom message)

2022-10-05 02:57 UTC, tonybaloney approved these changes

2022-10-05 02:58 UTC, tonybaloney commented
Great contribution, thank you

2022-10-05 02:58 UTC, merged