I added 2 rock names and 1 snake name
tonybaloney/vscode-pets pull request #214
Opened 2022-10-09 21:19 UTC by 5theawesome

My first pull request

2022-10-09 22:33 UTC, tonybaloney requested changes

2022-10-09 22:33 UTC, tonybaloney commented on src/common/names.ts
> +    [10, 'Misunderstood Animal who did nothing to you'],
Please remove this one. Such a long name is going to cause havoc. It's more of a sentence than a name :-)

2022-10-10 03:27 UTC, 5theawesome commented
Ok cool I'll change that

2023-01-24 02:46 UTC, remixie reviewed
Removed the long name.

2023-02-26 22:07 UTC, closed without merging