Added Interesting Pet Names.
tonybaloney/vscode-pets pull request #252
Opened 2022-10-12 15:43 UTC by ShabanaNaik

Hello @tonybaloney,
After a lot of interesting name searches, I came upon the Star buck's, Pokémon, Disney characters and many common names for Dog, Snake, Rocky, Zappy and Duck names.
I have added names that seemed logical or interesting based on the pet's visuals present in the extension.
And thank you for the extension I have been using it for a few days now when I feel tried or irritated while coding 😣. And the pets really made me feel at ease after playing with them😁😊. Especially the snake and duck. I really liked the whole snake on a cart (or 2 wheels) and duck with a jet pack and radio on it back with the sunglasses look 🤩.

2022-10-17 08:33 UTC, tonybaloney requested changes

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [28, 'Little Rey'],
Please remove the star wars references ( I don't want to be sued by Disney !)

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [18, 'The Anaconda'],
Please remove "The Anaconda"

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [17, 'My Python'],
Please remove "My Python"

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [12, 'Miss.Hiss'],
Please be consistent with the space after the `Mr.` and `Mrs.` I think they should all just have a space, e.g. `Mr Hiss`

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [29, 'Hiss Speed'],
I don't understand this one

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [22, 'SandaConda'],
Missing a space

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [19, 'Mr.Quack'],
Same as above re: spacing

2022-10-17 08:33 UTC, tonybaloney commented on src/common/names.ts
> +    [22, 'Rock On It!'],
Please remove the exclamation mark

2022-10-17 11:08 UTC, ShabanaNaik reviewed
I have made the changes as requested. Thank you for your patience.

2022-10-22 11:45 UTC, closed without merging

2022-10-22 11:47 UTC, ShabanaNaik commented
I have noticed this PR has conflicts with the real file that I am unable to understand. I would like to close this and open a new PR if that would possible after making necessary changes.