Add Chinese Translation
tonybaloney/vscode-pets pull request #266
Opened 2022-10-16 11:12 UTC by ashishkashyap31

Added Chinese translation.

2022-10-16 11:22 UTC, ashishkashyap31 commented
Solves #225  @tonybaloney .

2022-10-17 08:33 UTC, yihong0618 commented on package.nls.zh.json
> +  "vscodePets.rubber-duck": "橡皮鸭",
小黄鸭好一些？
little yellow duck maybe better? since we call it '小黄鸭调试'？

2022-10-17 08:33 UTC, yihong0618 commented on package.nls.zh.json
> +  "vscodePets.spawnPet": "产卵宠物",
产卵宠物不太好懂吧？
‘A bit hard to understand’ maybe a bit hard to understand for Chinese?

2022-10-17 09:11 UTC, BlackHole1 requested changes

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.nameYourPet": "命名您的宠物",
```suggestion
  "vscodePets.nameYourPet": "为您的宠物命名",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.selectPetToRemove": "选择宠物去除。",
```suggestion
  "vscodePets.selectPetToRemove": "选择要移除的宠物。",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.removePetsWithClosedPlayground": "已经创建了一个宠物游乐场。 现在，您可以使用\"Remove All Pets\"命令去除所有宠物。",
```suggestion
  "vscodePets.removePetsWithClosedPlayground": "已经创建了一个宠物游乐场。 现在，您可以使用 \"Remove All Pets\" 命令移除所有宠物。",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.spawnPetWithClosedPlayground": "已经创建了一个宠物游乐场。 现在，您可以使用\"Spawn Additional Pet\"命令添加更多宠物。",
```suggestion
  "vscodePets.spawnPetWithClosedPlayground": "已经创建了一个宠物游乐场。 现在，您可以使用 \"Spawn Additional Pet\" 命令添加更多宠物。",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.totoro": "托托罗",
```suggestion
  "vscodePets.totoro": "龙猫",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.clippy": "笨拙",
```suggestion
  "vscodePets.clippy": "回形针",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.cockatiel": "小鹦鹉",
```suggestion
  "vscodePets.cockatiel": "鹦鹉",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.zappy": "活泼的"
```suggestion
  "vscodePets.zappy": "zappy"

```

It is a name that we should not translate

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.spawnPet": "产卵宠物",
```suggestion
  "vscodePets.spawnPet": "创建宠物",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.cancelledSpawningPet": "取消产卵宠物",
```suggestion
  "vscodePets.cancelledSpawningPet": "取消创建宠物",

```

2022-10-17 09:11 UTC, BlackHole1 commented on package.nls.zh.json
> +  "vscodePets.leaveBlank": "留空白名称",
```suggestion
  "vscodePets.leaveBlank": "留空则随机一个名称",

```

2022-10-17 09:52 UTC, yihong0618 commented on package.nls.zh.json
> +  "vscodePets.totoro": "托托罗",
cool

2022-10-17 10:14 UTC, ashishkashyap31 commented
@BlackHole1 @yihong0618 , did the changes as requested, please review.

2022-10-17 10:25 UTC, yihong0618 approved these changes
LGTM nice job~

2022-10-17 10:37 UTC, tonybaloney approved these changes

2022-10-17 10:37 UTC, tonybaloney commented
Thanks everyone.

2022-10-17 10:37 UTC, merged