Add snail pet
tonybaloney/vscode-pets pull request #577
Opened 2024-06-12 04:48 UTC by WoofWoof0

Hi there, I want to contribute to this repo by adding a new feature (pet snail). This is my first open-source PR, let me know if there is any problem, perhaps some guidance would be nice too. :)

2024-06-12 05:13 UTC, tonybaloney requested changes
Please can you rename the GIFs so that they are all lower case. If you're using Windows you need to use the `git mv` command.

2024-06-12 05:13 UTC, tonybaloney commented on src/panel/pets.ts
> +            return new Snail(...standardPetArguments,PetSpeed.slow);
I think `verySlow` would be a better speed

2024-06-12 05:17 UTC, tonybaloney commented
This is a great PR, please can you look at my comments. Also please add an attribution for the artwork to README along with the others.

2024-06-14 03:56 UTC, WoofWoof0 commented
I had rename the gif files as requested.

2024-06-17 01:16 UTC, tonybaloney approved these changes

2024-06-17 01:17 UTC, tonybaloney approved these changes

2024-06-17 01:17 UTC, merged