diffrent speeds cant be friends
tonybaloney/vscode-pets pull request #599
Opened 2024-08-12 03:07 UTC by lahrims

1. Friendships are made with pets of similar speeds - add condition here https://github.com/tonybaloney/vscode-pets/blob/main/src/panel/pets.ts#L108-L110

added a speed threshold and the two pet speeds are compared against the threshould for them to be friends

2024-08-23 10:11 UTC, tonybaloney commented on src/panel/pets.ts
> +                const speed_difference = Math.abs(petInCollection.pet.speed - potentialFriend.pet.speed);
```suggestion
                const speedDifference = Math.abs(petInCollection.pet.speed - potentialFriend.pet.speed);
```

2024-08-23 10:11 UTC, tonybaloney commented on src/panel/pets.ts
> +                if (speed_difference > speedThreshold){
```suggestion
                if (speedDifference > speedThreshold){
```

2024-08-23 10:12 UTC, tonybaloney commented on src/panel/pets.ts
> +                }//Pet speeds are very different we cant be friends
```suggestion
                } //Pet speeds are very different; we cant be friends
```

2024-08-23 10:12 UTC, tonybaloney requested changes
Minor changes inline

2024-08-23 14:16 UTC, lahrims commented
@tonybaloney I see! I should have been more careful about the naming convention

2024-09-23 23:36 UTC, sharktrexer commented
Is there any update on this getting merged? I'm still having this issue that this fixes as of 9/23/2024.

2024-10-30 14:09 UTC, lahrims commented
Hi @tonybaloney
Just checking in to see if there is anything more required before this issue is merged. And if there are any other issues, I would love to contribute.

2024-11-01 08:10 UTC, tonybaloney commented
> Hi @tonybaloney
> 
> Just checking in to see if there is anything more required before this issue is merged. And if there are any other issues, I would love to contribute.

Sorry I'm just really busy at the moment.

2025-03-13 02:06 UTC, closed without merging